# Generated by Django 4.0.2 on 2022-02-08 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the position and establishment', max_length=100)),
                ('matching_positions', models.CharField(help_text='Tab-delimited list of positions to match candidates', max_length=100)),
                ('city', models.CharField(choices=[('mtjuliet', 'Mt. Juliet'), ('murfreesboro', 'Murfreesboro'), ('nashville', 'Nashville')], max_length=100)),
            ],
        ),
    ]
