# Generated by Django 4.0.2 on 2022-02-08 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='First and last name of candidate', max_length=100)),
                ('city', models.CharField(choices=[('mtjuliet', 'Mt. Juliet'), ('murfreesboro', 'Murfreesboro'), ('nashville', 'Nashville')], help_text='The city where the candidate lives', max_length=100)),
                ('positions', models.CharField(help_text='Tab-delimited list of position types that a candidate is seeking', max_length=200)),
            ],
        ),
    ]
